create DATABASE IF NOT EXISTS reports14;

USE reports14;

CREATE TABLE AREA (
  AREA_SEQ_CDG INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL
  , AREA_NOMBRE VARCHAR(80) NOT NULL UNIQUE
) ENGINE = INNODB;


CREATE TABLE TIPO_PARAMETRO_REPORTE (
  TPPR_SEQ_CDG INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL
  , TPPR_NOMBRE VARCHAR(50) NOT NULL UNIQUE
) ENGINE = INNODB;


CREATE TABLE CONTROLADOR (
  CTRL_SEQ_CDG INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL
  , CTRL_NOMBRE VARCHAR(60) NOT NULL UNIQUE
) ENGINE = INNODB; 


CREATE TABLE CONEXIONES (
  CONX_SEQ_CDG INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL
  , CTRL_SEQ_CDG INTEGER NOT NULL
  , CONX_NOMBRE VARCHAR(50) NOT NULL UNIQUE
  , CONX_URL VARCHAR(500) NOT NULL
  , CONX_USER VARCHAR (60) NULL
  , CONX_PASS VARCHAR(32) NULL
  , CONX_USUARIO_CREADOR VARCHAR(60) NOT NULL
  , CONX_FECHA_CREACION DATETIME NOT NULL
  , CONX_USUARIO_MODIFICADOR VARCHAR(60) NULL
  , CONX_FECHA_MODIFICACION DATETIME NULL
  , CONSTRAINT FK_CONTROLADOR FOREIGN KEY (CTRL_SEQ_CDG) REFERENCES CONTROLADOR(CTRL_SEQ_CDG)
) ENGINE = INNODB; 


CREATE TABLE REPORTE (
  RPTE_SEQ_CDG INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL
  , AREA_SEQ_CDG INTEGER NOT NULL
  , CONX_SEQ_CDG INTEGER NOT NULL
  , RPTE_NOMBRE VARCHAR(50) NOT NULL UNIQUE
  , RPTE_DESCRIPCION VARCHAR(500) NULL
  , RPTE_SQL TEXT NOT NULL
  , RPTE_ACTIVO BOOLEAN NOT NULL
  , RPTE_USUARIO_CREADOR VARCHAR(60) NOT NULL
  , RPTE_FECHA_CREACION DATETIME NOT NULL
  , RPTE_USUARIO_MODIFICADOR VARCHAR(60) NULL
  , RPTE_FECHA_MODIFICACION DATETIME NULL
  , CONSTRAINT FK_AREA FOREIGN KEY (AREA_SEQ_CDG) REFERENCES AREA(AREA_SEQ_CDG)
  , CONSTRAINT FK_CONEXION FOREIGN KEY (CONX_SEQ_CDG) REFERENCES CONEXIONES(CONX_SEQ_CDG)
) ENGINE = INNODB; 


CREATE TABLE PARAMETROS_REPORTE (
  PARE_SEQ_CDG INTEGER AUTO_INCREMENT PRIMARY KEY  NOT NULL
  , TPPR_SEQ_CDG INTEGER NOT NULL
  , RPTE_SEQ_CDG INTEGER NOT NULL
  , PARE_NOMBRE VARCHAR(50) NOT NULL
  , PARE_REQUERIDO BOOLEAN NULL
  , PARE_COMO BOOLEAN NULL
  , PARE_DATO1 VARCHAR(10) NULL
  , PARE_DATO2 VARCHAR(10) NULL
  , CONSTRAINT FK_TIPO_PARAMETRO_REPORTE FOREIGN KEY (TPPR_SEQ_CDG) REFERENCES TIPO_PARAMETRO_REPORTE(TPPR_SEQ_CDG)
  , CONSTRAINT FK_REPORTE FOREIGN KEY (RPTE_SEQ_CDG) REFERENCES REPORTE(RPTE_SEQ_CDG)
) ENGINE = INNODB; 


CREATE TABLE TIPO_RESPUESTA_REPORTE (
  TPRR_SEQ_CDG INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL
  , TPRR_NOMBRE VARCHAR(50) NOT NULL UNIQUE
) ENGINE = INNODB; 


CREATE TABLE LOG_REPORTES (
  LOG_SEQ_CDG INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL
  , TPRR_SEQ_CDG INTEGER NULL
  , LOG_NOMBRE VARCHAR(200) NOT NULL
  , LOG_HOST VARCHAR(60) NOT NULL
  , LOG_USUARIO VARCHAR (60) NULL
  , LOG_SQL TEXT NOT NULL
  , LOG_URL VARCHAR(200) NOT NULL
  , LOG_FECHA_INICIO_CONSULTA_DB DATETIME NOT NULL
  , LOG_FECHA_TERMINO_CONSULTA_DB DATETIME NULL
  , LOG_FECHA_INICIO_GENERACION_REPORTE DATETIME NULL
  , LOG_FECHA_TERMINO_GENERACION_REPORTE DATETIME NULL
  , LOG_DESCRIPCION VARCHAR(200) NULL
  , CONSTRAINT FK_TIPO_RESPUESTA_REPORTE FOREIGN KEY (TPRR_SEQ_CDG) REFERENCES TIPO_RESPUESTA_REPORTE(TPRR_SEQ_CDG)
) ENGINE = INNODB; 



INSERT INTO TIPO_RESPUESTA_REPORTE (TPRR_NOMBRE) SELECT 'OK';
INSERT INTO TIPO_RESPUESTA_REPORTE (TPRR_NOMBRE) SELECT 'Error General';
INSERT INTO TIPO_RESPUESTA_REPORTE (TPRR_NOMBRE) SELECT 'Alerta';
INSERT INTO TIPO_RESPUESTA_REPORTE (TPRR_NOMBRE) SELECT 'Error en SQL';
INSERT INTO TIPO_RESPUESTA_REPORTE (TPRR_NOMBRE) SELECT 'Error en parametros';
INSERT INTO TIPO_RESPUESTA_REPORTE (TPRR_NOMBRE) SELECT 'Error generando reporte';
INSERT INTO TIPO_RESPUESTA_REPORTE (TPRR_NOMBRE) SELECT 'Driver no soportado';


INSERT INTO AREA (AREA_NOMBRE) SELECT 'Operaciones';
INSERT INTO AREA (AREA_NOMBRE) SELECT 'Riesgo';
INSERT INTO AREA (AREA_NOMBRE) SELECT 'Cobranza';
INSERT INTO AREA (AREA_NOMBRE) SELECT 'Comercial';
INSERT INTO AREA (AREA_NOMBRE) SELECT 'PostVenta';
INSERT INTO AREA (AREA_NOMBRE) SELECT 'Gerencia';

INSERT INTO CONTROLADOR (CTRL_NOMBRE) SELECT 'PostgreSQL';
INSERT INTO CONTROLADOR (CTRL_NOMBRE) SELECT 'SQLServer';
INSERT INTO CONTROLADOR (CTRL_NOMBRE) SELECT 'MySQL';
INSERT INTO CONTROLADOR (CTRL_NOMBRE) SELECT 'Oracle';
INSERT INTO CONTROLADOR (CTRL_NOMBRE) SELECT 'JDTs';



INSERT INTO TIPO_PARAMETRO_REPORTE (TPPR_NOMBRE) SELECT 'Alfanumerico';
INSERT INTO TIPO_PARAMETRO_REPORTE (TPPR_NOMBRE) SELECT 'Fecha';
INSERT INTO TIPO_PARAMETRO_REPORTE (TPPR_NOMBRE) SELECT 'Numerico';
INSERT INTO TIPO_PARAMETRO_REPORTE (TPPR_NOMBRE) SELECT 'Booleano';
INSERT INTO TIPO_PARAMETRO_REPORTE (TPPR_NOMBRE) SELECT 'Rango Fechas';
INSERT INTO TIPO_PARAMETRO_REPORTE (TPPR_NOMBRE) SELECT 'Alfanumerico+Like';


